project_id = "osbyqrzbfcojbqjmwhej"

[functions.crop-recommendation]
verify_jwt = true

[functions.walle-chatbot]
verify_jwt = true

[functions.file-reader]
verify_jwt = true

[functions.parse-soil-pdf]
verify_jwt = true